"""CI workflow generation: the same checks the agent runs locally, re-run as objective evidence."""

import yaml

from agentic_init.blueprint import Blueprint
from agentic_init.config import Commands
from agentic_init.targets.base import FileOp, Strategy

WORKFLOW_PATH = ".github/workflows/agentic-checks.yml"
PR_TEMPLATE_PATH = ".github/pull_request_template.md"
E2E_LEVEL = 2
SECURITY_LEVEL = 2

CHECKOUT = {"name": "Checkout", "uses": "actions/checkout@v4"}
SETUP = {
    "pnpm": [
        {"name": "Set up pnpm", "uses": "pnpm/action-setup@v4"},
        {"name": "Set up Node", "uses": "actions/setup-node@v4", "with": {"node-version": "22", "cache": "pnpm"}},
    ],
    "yarn": [{"name": "Set up Node", "uses": "actions/setup-node@v4", "with": {"node-version": "22", "cache": "yarn"}}],
    "npm": [{"name": "Set up Node", "uses": "actions/setup-node@v4", "with": {"node-version": "22", "cache": "npm"}}],
    "bun": [{"name": "Set up Bun", "uses": "oven-sh/setup-bun@v2"}],
    "uv": [{"name": "Set up uv", "uses": "astral-sh/setup-uv@v5", "with": {"enable-cache": True}}],
    "poetry": [{"name": "Set up Python", "uses": "actions/setup-python@v5", "with": {"python-version": "3.12"}}],
    "pipenv": [{"name": "Set up Python", "uses": "actions/setup-python@v5", "with": {"python-version": "3.12"}}],
    "pip": [{"name": "Set up Python", "uses": "actions/setup-python@v5", "with": {"python-version": "3.12"}}],
    "cargo": [{"name": "Set up Rust", "uses": "dtolnay/rust-toolchain@stable"}],
    "go": [{"name": "Set up Go", "uses": "actions/setup-go@v5", "with": {"go-version": "stable"}}],
}
# Pipeline order from the operating model: static checks first, then tests, then build.
CHECK_ORDER = (("lint", "Lint"), ("typecheck", "Typecheck"), ("test", "Test"), ("build", "Build"))


def _setup_steps(blueprint: Blueprint) -> list[dict]:
    for manager in blueprint.detection.stack.package_managers:
        if manager in SETUP:
            return SETUP[manager]
    return []


def _install(commands: Commands) -> list[dict]:
    return [{"name": "Install", "run": commands.install}] if commands.install else []


def _checks_job(blueprint: Blueprint) -> dict:
    commands = blueprint.commands
    steps = [CHECKOUT, *_setup_steps(blueprint), *_install(commands)]
    steps += [
        {"name": label, "run": getattr(commands, key)} for key, label in CHECK_ORDER if getattr(commands, key, None)
    ]
    return {"name": "checks", "runs-on": "ubuntu-latest", "steps": steps}


def _e2e_job(blueprint: Blueprint) -> dict:
    steps = [CHECKOUT, *_setup_steps(blueprint), *_install(blueprint.commands)]
    if "playwright" in (blueprint.commands.e2e or ""):
        steps.append({"name": "Install browsers", "run": "npx playwright install --with-deps"})
    steps.append({"name": "End-to-end", "run": blueprint.commands.e2e})
    return {"name": "e2e", "runs-on": "ubuntu-latest", "steps": steps}


def _security_job() -> dict:
    return {
        "name": "security",
        "runs-on": "ubuntu-latest",
        "if": "github.event_name == 'pull_request'",
        "permissions": {"contents": "read", "pull-requests": "write"},
        "steps": [
            CHECKOUT,
            {
                "name": "Dependency review",
                "uses": "actions/dependency-review-action@v4",
                "with": {"fail-on-severity": "high"},
            },
        ],
    }


def workflow(blueprint: Blueprint) -> str:
    jobs = {"checks": _checks_job(blueprint)}
    if blueprint.config.level >= E2E_LEVEL and blueprint.commands.e2e:
        jobs["e2e"] = _e2e_job(blueprint)
    if blueprint.config.level >= SECURITY_LEVEL:
        jobs["security"] = _security_job()
    document = {
        "name": "agentic checks",
        "on": {"push": {"branches": [blueprint.detection.git.default_branch]}, "pull_request": {}},
        "permissions": {"contents": "read"},
        "concurrency": {"group": "${{ github.workflow }}-${{ github.ref }}", "cancel-in-progress": True},
        "jobs": jobs,
    }
    header = (
        "# Generated by agentic_init from the commands in CLAUDE.md.\n"
        "# The agent runs these locally; CI re-runs them as independent evidence.\n"
    )
    # PyYAML quotes the `on` key because YAML 1.1 reads it as a boolean; GitHub accepts `'on':`.
    return header + yaml.safe_dump(document, sort_keys=False, width=1000, default_flow_style=False)


PR_TEMPLATE = """## Summary

<!-- What changed and why. Link the story or issue. -->

## Architecture impact

<!-- Boundaries, dependencies, public API. "None" is a valid answer. -->

## Migration impact

<!-- Schema, data, config or deployment steps. "None" is a valid answer. -->

## Evidence

| Check | Command | Result |
| --- | --- | --- |
{rows}

## Security considerations

<!-- Authn/authz, input handling, secrets, data exposure, new dependencies. -->

## Performance considerations

<!-- Hot paths, queries, payload sizes. -->

## Residual risk

<!-- What could still be wrong, and how it would show up. -->
"""

EVIDENCE_ROWS = (("Lint", "lint"), ("Typecheck", "typecheck"), ("Tests", "test"), ("End-to-end", "e2e"))


def pull_request_template(blueprint: Blueprint) -> str:
    rows = [
        f"| {label} | `{getattr(blueprint.commands, key)}` | |"
        for label, key in EVIDENCE_ROWS
        if getattr(blueprint.commands, key, None)
    ] or ["| | | |"]
    return PR_TEMPLATE.format(rows="\n".join(rows))


def render_ci(blueprint: Blueprint) -> list[FileOp]:
    if not blueprint.ci:
        return []
    return [
        FileOp(WORKFLOW_PATH, Strategy.OWNED, content=workflow(blueprint)),
        FileOp(PR_TEMPLATE_PATH, Strategy.SEED, content=pull_request_template(blueprint)),
    ]
